### ISSUE TITLE
Workspace内でrustのeditionなどを統一する

### ISSUE THREAD

**Issue by comavius** [traP-jp/traO-Judge-judge#199]

**Comment by comavius** [comment]
versionも
```toml
[package]
...
version = { workspace = true }
edition = { workspace = true }
```
